#TRAINING_SIZE = 200
#VALIDATION_SIZE = 2500

TOTAL_SIZE = int(100*0.9)
TRAINING_SIZE = int(TOTAL_SIZE*200/2500)
VALIDATION_SIZE = TOTAL_SIZE-TRAINING_SIZE

RM_GRANULARITY = 300
REGRESSION = "sklearn.neighbors.KNeighborsRegressor()"

NUM_INDEPENDENT = 1
NUM_DEPENDENT = 1
