#TRAINING_SIZES = range(40, 440, 40)
#VALIDATION_SIZE = 200
#RM_GRANULARITIES = range(15, 65, 10)

TRAINING_SIZE = 40
VALIDATION_SIZE = 10
RM_GRANULARITY = 20
REGRESSION = "sklearn.neighbors.KNeighborsRegressor()"

NUM_INDEPENDENT = 5
NUM_DEPENDENT = 2
